export const clericEquipment = [
  [
    "Cudgel (Damage: 1d4, Qualities: Blunt, Melee)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross"
  ],
  [
    "Cudgel (Damage: 1d4, Qualities: Blunt, Melee)",
    "Shield",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Wooden Cross"
  ],
  [
    "Mace (Damage: 1d6, Qualities: Blunt, Melee)",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross"
  ],
  [
    "Quarter-Staff (Damage: 1d4, Qualities: Blunt, Melee, Slow, Two-handed)",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "12 Iron Spikes",
    "Wooden Cross",
    "3 Stakes & Mallet",
    "Steel Mirror"
  ],
  [
    "Chain Armor",
    "War Hammer (Damage: 1d6, Qualities: Blunt, Melee)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "2 Small Sacks"
  ],
  [
    "Chain Armor",
    "Shield",
    "Mace (Damage: 1d6, Qualities: Blunt, Melee)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Wooden Cross",
    "2 Small Sacks"
  ],
  [
    "Chain Armor",
    "Shield",
    "War Hammer (Damage: 1d6, Qualities: Blunt, Melee)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "2 Small Sacks",
    "3 Stakes & Mallet",
    "Steel Mirror"
  ],
  [
    "Plate Armor",
    "Shield",
    "Mace (Damage: 1d6, Qualities: Blunt, Melee)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Wooden Cross"
  ],
  [
    "Plate Armor",
    "Shield",
    "War Hammer (Damage: 1d6, Qualities: Blunt, Melee)",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "Small Sack"
  ],
  [
    "Plate Armor",
    "Quarter-Staff (Damage: 1d4, Qualities: Blunt, Melee, Slow, Two-handed)",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Silver Cross"
  ],
  [
    "Cudgel (Damage: 1d4, Qualities: Blunt, Melee)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "Scroll"
  ],
  [
    "Plate Armor",
    "Shield",
    "Mace (Damage: 1d6, Qualities: Blunt, Melee)",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Silver Cross"
  ],
  [
    "Leather Armor",
    "Mace (Damage: 1d6, Qualities: Blunt, Melee)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "Scroll",
    "2 Flasks oil"
  ],
  [
    "Plate Armor",
    "Shield",
    "Helmet",
    "War Hammer (Damage: 1d6, Qualities: Blunt, Melee)",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Silver Cross",
    "3 Stakes & Mallet",
    "Steel Mirror"
  ],
  [
    "Chain Armor",
    "War Hammer (Damage: 1d6, Qualities: Blunt, Melee)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "Scroll"
  ],
  [
    "Plate Armor",
    "Shield",
    "Helmet",
    "Mace (Damage: 1d6, Qualities: Blunt, Melee)",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Silver Cross",
    "Vial Holy Water (Damage: 1d8, Qualities: Missile (5’-10’ / 11’-30’ / 31’-50’), Splash weapon)",
    "12 Iron Spikes",
    "3 Stakes & Mallet",
    "Small Sack"
  ]
];

export const fighterEquipment = [
  [
    "Spear (Damage: 1d6, Qualities: Brace, Melee, Missile (5’-20’ / 21’-40’ / 41’-60’))",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Cudgel (Damage: 1d4, Qualities: Blunt, Melee)",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Leather Armor",
    "Morning Star (Damage: 1d6, Qualities: Blunt, Melee)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Leather Armor",
    "Battle axe (Damage: 1d8, Qualities: Melee, Slow, Two-handed)",
    "Hand axe (Damage: 1d6, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Sling (Damage: 1d4, Qualities: Blunt, Missile (5’-40’ / 41’-80’ / 81’-160’))",
    "Pouch With Sling Bullets (d20 usage die)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Chain Armor",
    "Spear (Damage: 1d6, Qualities: Brace, Melee, Missile (5’-20’ / 21’-40’ / 41’-60’))",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Sling (Damage: 1d4, Qualities: Blunt, Missile (5’-40’ / 41’-80’ / 81’-160’))",
    "Pouch With Sling Bullets (d20 usage die)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Chain Armor",
    "Shield",
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Chain Armor",
    "Spear (Damage: 1d6, Qualities: Brace, Melee, Missile (5’-20’ / 21’-40’ / 41’-60’))",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case With Bolts (d20 usage die)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Plate Armor",
    "Shield",
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Plate Armor",
    "Two-Handed Sword (Damage: 1d8, Qualities: Melee)",
    "3 Daggers (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "2 Flasks oil"
  ],
  [
    "Plate Armor",
    "Shield",
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case With Bolts (d20 usage die)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Plate Armor",
    "Flail (Damage: 1d6, Qualities: Blunt, Melee)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Short bow (Damage: 1d6, Qualities: Missile (5’-50’ / 51’-100’ / 101’-150’), Two-handed)",
    "Quiver of Arrows (d20 usage die)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Small Sack"
  ],
  [
    "Plate Armor",
    "Shield",
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case With Bolts (d20 usage die)",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Plate Armor",
    "Helmet",
    "2 Battle Axe (Damage: 1d8, Qualities: Melee, Slow, Two-handed)s",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case With Bolts (d20 usage die)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "5 Flasks oil"
  ],
  [
    "Plate Armor",
    "Two-Handed Sword (Damage: 1d8, Qualities: Melee)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Short bow (Damage: 1d6, Qualities: Missile (5’-50’ / 51’-100’ / 101’-150’), Two-handed)",
    "Quiver of Arrows (d20 usage die)",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "2 Small Sacks"
  ],
  [
    "Plate Armor",
    "Halberd (Damage: 1d10, Qualities: Brace, Melee, Slow, Two-handed)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Long bow (Damage: 1d6, Qualities: Missile (5’-70’ / 71’-140’ / 141’-210’), Two-handed)",
    "Quiver of Arrows (d20 usage die)",
    "Silver Tipped Arrows (d4 usage die)",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Plate Armor",
    "Shield",
    "Helmet",
    "Sword (Damage: 1d8, Qualities: Melee)",
    "2 Daggers (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case With Bolts (d20 usage die)",
    "Silver Tipped Bolts (d4 usage die)",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ]
];

export const magicUserEquipment = [
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "2 Daggers (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "2 Flasks oil",
    "50' Rope"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Vial of Holy Water"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "5 Flasks of oil",
    "Silver Mirror",
    "Belladona"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "2 Vials Holy Water (Damage: 1d8, Qualities: Missile (5’-10’ / 11’-30’ / 31’-50’), Splash weapon)"
  ],
  [
    "3 Daggers (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Vial of Holy Water"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "2 Vials Holy Water (Damage: 1d8, Qualities: Missile (5’-10’ / 11’-30’ / 31’-50’), Splash weapon)"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "10' Pole"
  ],
  [
    "2 Daggers (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "50' Rope"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "10' Pole"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "50' Rope"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "10' Pole"
  ],
  [
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "50' Rope"
  ]
];

export const thiefEquipment = [
  [
    "Cudgel (Damage: 1d4, Qualities: Blunt, Melee)",
    "Sling (Damage: 1d4, Qualities: Blunt, Missile (5’-40’ / 41’-80’ / 81’-160’))",
    "Pouch With Sling Bullets (d20 usage die)",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Cudgel (Damage: 1d4, Qualities: Blunt, Melee)",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Cudgel (Damage: 1d4, Qualities: Blunt, Melee)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Sling (Damage: 1d4, Qualities: Blunt, Missile (5’-40’ / 41’-80’ / 81’-160’))",
    "Pouch With Sling Bullets (d20 usage die)",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Cudgel (Damage: 1d4, Qualities: Blunt, Melee)",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case With Bolts (d20 usage die)",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case of 30 Bolts",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "2 Daggers (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Short bow (Damage: 1d6, Qualities: Missile (5’-50’ / 51’-100’ / 101’-150’), Two-handed)",
    "Quiver of Arrows (d20 usage die)",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case of 30 Bolts",
    "Silver Tipped Bolts (d4 usage die)",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Dagger (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Short bow (Damage: 1d6, Qualities: Missile (5’-50’ / 51’-100’ / 101’-150’), Two-handed)",
    "Quiver of Arrows (d20 usage die)",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case of 30 Bolts",
    "Silver Tipped Bolts (d4 usage die)",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Short bow (Damage: 1d6, Qualities: Missile (5’-50’ / 51’-100’ / 101’-150’), Two-handed)",
    "Quiver of Arrows (d20 usage die)",
    "Silver Tipped Arrows (d4 usage die)",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "4 Daggers (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "Crossbow (Damage: 1d6, Qualities: Missile (5’-80’ / 81’-160’ / 161’-240’), Reload, Slow, Two-handed)",
    "Case of 30 Bolts",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword (Damage: 1d8, Qualities: Melee)",
    "3 Daggers (Damage: 1d4, Qualities: Melee, Missile (5’-10’ / 11’-20’ / 21’-30’))",
    "Short bow (Damage: 1d6, Qualities: Missile (5’-50’ / 51’-100’ / 101’-150’), Two-handed)",
    "Quiver of Arrows (d20 usage die)",
    "Silver Tipped Arrows (d4 usage die)",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ]
];
