export const clericEquipment = [
  [
    "Cudgel",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross"
  ],
  [
    "Cudgel",
    "Shield",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Wooden Cross"
  ],
  [
    "Mace",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross"
  ],
  [
    "Quarter-Staff",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "12 Iron Spikes",
    "Wooden Cross",
    "3 Stakes & Mallet",
    "Steel Mirror"
  ],
  [
    "Chain Armor",
    "War Hammer",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "2 Small Sacks"
  ],
  [
    "Chain Armor",
    "Shield",
    "Mace",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Wooden Cross",
    "2 Small Sacks"
  ],
  [
    "Chain Armor",
    "Shield",
    "War Hammer",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "2 Small Sacks",
    "3 Stakes & Mallet",
    "Steel Mirror"
  ],
  [
    "Plate Armor",
    "Shield",
    "Mace",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Wooden Cross"
  ],
  [
    "Plate Armor",
    "Shield",
    "War Hammer",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "Small Sack"
  ],
  [
    "Plate Armor",
    "Quarter-Staff",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Silver Cross"
  ],
  [
    "Cudgel",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "Scroll"
  ],
  [
    "Plate Armor",
    "Shield",
    "Mace",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Silver Cross"
  ],
  [
    "Leather Armor",
    "Mace",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "Scroll",
    "2 Flasks oil"
  ],
  [
    "Plate Armor",
    "Shield",
    "Helmet",
    "War Hammer",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Silver Cross",
    "3 Stakes & Mallet",
    "Steel Mirror"
  ],
  [
    "Chain Armor",
    "War Hammer",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Wooden Cross",
    "Scroll"
  ],
  [
    "Plate Armor",
    "Shield",
    "Helmet",
    "Mace",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Silver Cross",
    "Vial Holy Water",
    "12 Iron Spikes",
    "3 Stakes & Mallet",
    "Small Sack"
  ]
];

export const fighterEquipment = [
  [
    "Spear",
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Cudgel",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Leather Armor",
    "Morning Star",
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Leather Armor",
    "Battle axe",
    "Hand axe",
    "Dagger",
    "Sling",
    "Pouch With 20 Sling Bullets",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Chain Armor",
    "Spear",
    "Dagger",
    "Sling",
    "Pouch With 20 Sling Bullets",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Chain Armor",
    "Shield",
    "Sword",
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Chain Armor",
    "Spear",
    "Light Crossbow",
    "Case With 30 Quarrels",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Plate Armor",
    "Shield",
    "Sword",
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Plate Armor",
    "Two-Handed Sword",
    "3 Daggers",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "2 Flasks oil"
  ],
  [
    "Plate Armor",
    "Shield",
    "Sword",
    "Light Crossbow",
    "Case With 30 Quarrels",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Plate Armor",
    "Flail",
    "Dagger",
    "35 Short bow",
    "Quiver of 20 Arrows",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Small Sack"
  ],
  [
    "Plate Armor",
    "Shield",
    "Sword",
    "Light Crossbow",
    "Case With 30 Quarrels",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Plate Armor",
    "Helmet",
    "2 Battle Axes",
    "Dagger",
    "Light Crossbow",
    "Case With 30 Quarrels",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "5 Flasks oil"
  ],
  [
    "Plate Armor",
    "Two-Handed Sword",
    "Dagger",
    "Short bow",
    "Quiver of 20 Arrows",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "2 Small Sacks"
  ],
  [
    "Plate Armor",
    "Halberd",
    "Dagger",
    "Long bow",
    "Quiver of 20 Arrows",
    "2 Silver Tipped Arrows",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Plate Armor",
    "Shield",
    "Helmet",
    "Sword",
    "2 Daggers",
    "Light Crossbow",
    "Case With 30 Quarrels",
    "4 Silver Tipped Quarrels",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ]
];

export const magicUserEquipment = [
  [
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "2 Daggers",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "2 Flasks oil",
    "50' Rope"
  ],
  [
    "Dagger",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "Vial of Holy Water"
  ],
  [
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "5 Flasks of oil",
    "Silver Mirror",
    "Belladona"
  ],
  [
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "2 Vials Holy Water"
  ],
  [
    "3 Daggers",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole",
    "Vial of Holy Water"
  ],
  [
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope",
    "2 Vials Holy Water"
  ],
  [
    "Dagger",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Dagger",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Dagger",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "10' Pole"
  ],
  [
    "2 Daggers",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "50' Rope"
  ],
  [
    "Dagger",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "10' Pole"
  ],
  [
    "Dagger",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "50' Rope"
  ],
  [
    "Dagger",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "10' Pole"
  ],
  [
    "Dagger",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "Scroll",
    "50' Rope"
  ]
];

export const thiefEquipment = [
  [
    "Cudgel",
    "Sling",
    "Pouch With 20 Sling Bullets",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Cudgel",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Cudgel",
    "Dagger",
    "Sling",
    "Pouch With 20 Sling Bullets",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword",
    "Dagger",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Cudgel",
    "Light Crossbow",
    "Case With 30 Quarrels",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword",
    "Light Crossbow",
    "Case of 30 Quarrels",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword",
    "2 Daggers",
    "35 Short bow",
    "Quiver of 20 Arrows",
    "Leather Armor",
    "6 Torches",
    "Backpack",
    "Waterskin",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword",
    "Dagger",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword",
    "Light Crossbow",
    "Case of 30 Quarrels",
    "2 Silver Tipped Quarrels",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword",
    "Dagger",
    "Short bow",
    "Quiver of 20 Arrows",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword",
    "Light Crossbow",
    "Case of 30 Quarrels",
    "6 Silver Tipped Quarrels",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword",
    "Short bow",
    "Quiver of 20 Arrows",
    "6 Silver Tipped Arrows",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword",
    "4 Daggers",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ],
  [
    "Sword",
    "Light Crossbow",
    "Case of 30 Quarrels",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "50' Rope"
  ],
  [
    "Sword",
    "3 Daggers",
    "Short bow",
    "Quiver of 20 Arrows",
    "8 Silver Tipped Arrows",
    "Leather Armor",
    "Backpack",
    "Waterskin",
    "Lantern",
    "4 Flasks oil",
    "Travel rations (1 day)",
    "Travel rations (1 day)",
    "10' Pole"
  ]
];
