export const gear = [
  "<strong>Air bladder</strong>",
  "<strong>Bear trap</strong>",
  "<strong>Shovel</strong>",
  "<strong>Bellows</strong>",
  "<strong>Grease</strong>",
  "<strong>Saw</strong>",
  "<strong>Bucket</strong>",
  "<strong>Caltrops</strong>",
  "<strong>Chisel</strong>",
  "<strong>Drill</strong>",
  "<strong>Fishing rod</strong>",
  "<strong>Marbles</strong>",
  "<strong>Glue</strong>",
  "<strong>Pick</strong>",
  "<strong>Hourglass</strong>",
  "<strong>Net</strong>",
  "<strong>Tongs</strong>",
  "<strong>Lockpicks</strong>",
  "<strong>Metal file</strong>",
  "<strong>Nails</strong>",
  "<strong>Pulleys</strong>",
  "<strong>Candles, 5</strong>",
  "<strong>10' Chain</strong>",
  "<strong>Chalk, 10</strong>",
  "<strong>Crowbar</strong>",
  "<strong>Tinderbox</strong>",
  "<strong>Grappling hook</strong>",
  "<strong>Hammer</strong>",
  "<strong>Lantern</strong>",
  "<strong>Padlock</strong>",
  "<strong>Manacles</strong>",
  "<strong>Mirror</strong>",
  "<strong>Tent</strong>",
  "<strong>Incense</strong>",
  "<strong>Sponge</strong>",
  "<strong>Lens</strong>",
  "<strong>Perfume</strong>",
  "<strong>Horn</strong>",
  "<strong>Bottle</strong>",
  "<strong>Soap</strong>",
  "<strong>Spyglass</strong>",
  "<strong>Tar pot</strong>",
  "<strong>300' Twine</strong>",
  "<strong>Fake jewels</strong>",
  "<strong>Blank book</strong>",
  "<strong>Card deck</strong>",
  "<strong>Dice set</strong>",
  "<strong>Cook pots</strong>",
  "<strong>Face paint</strong>",
  "<strong>Whistle</strong>",
  "<strong>Instrument</strong>",
  "<strong>Quill & Ink</strong>",
  "<strong>Small bell</strong>"
];

export const instruments = [
  "<strong>Bagpipe</strong>",
  "<strong>Bladder Pipe</strong>",
  "<strong>Castanets</strong>",
  "<strong>Crumhorn</strong>",
  "<strong>Dulcimer</strong>",
  "<strong>Gemshorn</strong>",
  "<strong>Harp</strong>",
  "<strong>Hurdy-gurdy</strong>",
  "<strong>Lizard</strong>",
  "<strong>Lute</strong>",
  "<strong>Lyre</strong>",
  "<strong>Mandolin</strong>",
  "<strong>Maracas</strong>",
  "<strong>Psaltery</strong>",
  "<strong>Sacbut</strong>",
  "<strong>Serpent</strong>",
  "<strong>Shofar</strong>",
  "<strong>Sitar</strong>",
  "<strong>Viol</strong>",
  "<strong>Zink</strong>"
];
