export const gear = [
  "<strong>Air Bladder</strong>",
  "<strong>Bear Trap</strong>",
  "<strong>Shovel</strong>",
  "<strong>Bellows</strong>",
  "<strong>Grease</strong>",
  "<strong>Saw</strong>",
  "<strong>Bucket</strong>",
  "<strong>Caltrops</strong>",
  "<strong>Chisel</strong>",
  "<strong>Drill</strong>",
  "<strong>Fishing rod</strong>",
  "<strong>Marbles</strong>",
  "<strong>Glue</strong>",
  "<strong>Pick</strong>",
  "<strong>Hourglass</strong>",
  "<strong>Net</strong>",
  "<strong>Tongs</strong>",
  "<strong>Lockpicks</strong>",
  "<strong>Metal File</strong>",
  "<strong>Nails</strong>",
  "<strong>Pulleys</strong>",
  "<strong>Candles, 5</strong>",
  "<strong>10' Chain</strong>",
  "<strong>Chalk, 10</strong>",
  "<strong>Crowbar</strong>",
  "<strong>Tinderbox</strong>",
  "<strong>Grappling Hook</strong>",
  "<strong>Hammer</strong>",
  "<strong>Padlock</strong>",
  "<strong>Manacles</strong>",
  "<strong>Mirror</strong>",
  "<strong>Tent</strong>",
  "<strong>Incense</strong>",
  "<strong>Sponge</strong>",
  "<strong>Lens</strong>",
  "<strong>Perfume</strong>",
  "<strong>Horn</strong>",
  "<strong>Bottle</strong>",
  "<strong>Soap</strong>",
  "<strong>Spyglass</strong>",
  "<strong>Tar Pot</strong>",
  "<strong>300' Twine</strong>",
  "<strong>Fake Jewels</strong>",
  "<strong>Blank Book</strong>",
  "<strong>Card Deck</strong>",
  "<strong>Dice Set</strong>",
  "<strong>Cook Pots</strong>",
  "<strong>Face Paint</strong>",
  "<strong>Whistle</strong>",
  "<strong>Instrument</strong>",
  "<strong>Quill & Ink</strong>",
  "<strong>Small Bell</strong>",
  "<strong>Waterskin</strong>",
  "<strong>3 Stakes and Mallet</strong>",
  "<strong>50' Rope</strong>",
  "<strong>10' Pole</strong>",
  "<strong>6 Torches</strong>",
  "<strong>Small Sack</strong> (holds 1 slot)",
  "<strong>Wolfsbane</strong> (d4 usage die)",
  "<strong>Belladonna</strong> (d4 usage die)",
  "<strong>Lantern</strong>",
  "<strong>Oil Flask</strong>",
  "<strong>Disguise Kit</strong>",
  "<strong>Signet Ring</strong>",
  "<strong>Military Rank Insignia</strong>",
  "<strong>Small Animal Skull</strong>",
  "<strong>50' Silk Rope</strong>",
  "<strong>Broken Blade</strong>",
  "<strong>Small Knife</strong>",
  "<strong>Pet Mouse</strong>",
  "<strong>Smoking Pipe</strong>",
  "<strong>Shiny Stone</strong>",
  "<strong>Shrunken Head</strong>",
  "<strong>Jar</strong>",
  "<strong>Small Sack of Rats</strong>"
];

export const instruments = [
  "<strong>Air Horn</strong>",
  "<strong>Bagpipe</strong>",
  "<strong>Bladder Pipe</strong>",
  "<strong>Castanets</strong>",
  "<strong>Crumhorn</strong>",
  "<strong>Dulcimer</strong>",
  "<strong>Gemshorn</strong>",
  "<strong>Harp</strong>",
  "<strong>Harmonica</strong>",
  "<strong>Hurdy-gurdy</strong>",
  "<strong>Kazoo</strong>",
  "<strong>Lizard</strong>",
  "<strong>Lute</strong>",
  "<strong>Lyre</strong>",
  "<strong>Mandolin</strong>",
  "<strong>Maracas</strong>",
  "<strong>Ocarina</strong>",
  "<strong>Pan Flute</strong>",
  "<strong>Psaltery</strong>",
  "<strong>Sacbut</strong>",
  "<strong>Serpent</strong>",
  "<strong>Shofar</strong>",
  "<strong>Sitar</strong>",
  "<strong>Viol</strong>",
  "<strong>Vuvuzela</strong>",
  "<strong>Zink</strong>"
];

export const burrowingMammals = [
  "<strong>Praire Dog</strong>",
  "<strong>Gopher</strong>",
  "<strong>Badger</strong>",
  "<strong>Skunk</strong>",
  "<strong>Armadillo</strong>",
  "<strong>Wombat</strong>",
  "<strong>Aardvark</strong>",
  "<strong>Mongoose</strong>",
  "<strong>Groundhog</strong>",
  "<strong>Mole</strong>"
];
