/**
 * Include basic spells WITH rules
 */
export const spells = [
  "Detect Magic\nDuration: 2 turns\nRange: 60’\nEnchanted objects, areas, or creatures are caused to glow. Both permanent and temporary enchantments are revealed.",
  "Hold Portal\nDuration: 2d6 turns\nRange: 10’\nThis spell magically holds shut a door, gate, window, or other kind of portal.\n  A knock spell opens the held portal instantly.\n  Creatures with at least 3 Hit Dice more than the caster can open the held portal with one round of effort.",
  "Read Magic\nDuration: 1 turn\nRange: The caster\nBy means of read magic, the caster can decipher magical inscriptions or runes, as follows:\n  The magical script of a scroll of arcane spells can be understood. The caster is then able to activate the scroll at any time in the future.\n  A spell book written by another arcane spell caster can be deciphered.\n  Runes or magical words inscribed on an object or surface can be understood.\nOnce the caster has read a magical inscription using read magic, he or she is thereafter able to read that particular writing without recourse to the use of this spell.",
  "Read Languages\nDuration: 2 turns\nRange: The caster\nFor the duration of this spell, the caster may read any language, coded message, map, or other set of written instructions. This spell does not grant any ability to speak unknown languages.",
  "Protection from Evil\nDuration: 6 turns\nRange: The caster\nThis spell wards the caster from attacks by creatures of another alignment, as follows:\n  The caster gains a +1 bonus to saving throws against attacks or special abilities of affected creatures.\n  Affected creatures’ attacks against the caster are penalised by -1.\nAdditionally, the spell prevents enchanted, constructed, or summoned creatures from attacking the caster in melee, though they may still make ranged attacks. If the caster engages such a creature in melee, this protection is broken (the caster still gains the bonuses to saving throws and attack rolls mentioned above).",
  "Light (Darkness)\nDuration: 6 turns +1 per level\nRange: 120’\nThis spell has three usages:\n  1. Conjuring light in a 15’ radius. The magical light is sufficient for reading, but is not as bright as daylight. The spell may be cast upon an object, in which case, the light moves with the object.\n  2. Blinding a creature by casting the spell upon its eyes. If the target fails a saving throw versus spells, it is blinded for the duration. A blind creature cannot attack.\n  3. Cancelling a darkness spell\nReversed: Darkness\nCreates a 15’ radius area of magical blackness, preventing normal sight (but not infravision). Like light, it may alternatively be used to blind creatures or to dispel a light spell.",
  "Charm Person\nDuration: One or more days (see below)\nRange: 120’\nA single, humanoid creature must save versus spells or be charmed, as follows:\n  The subject regards the caster as its trusted friend and ally and will come to the caster’s defence.\n  If they share a language, the caster may give the charmed creature commands, which it will obey.\n  Actions that the charmed creature wouldn’t ordinarily do, based on its nature or alignment, may be abstained from.\n  An affected creature never obeys suicidal or obviously harmful orders.\nHumanoids of greater than 4+1 HD and undead are not affected.\nThe charm lasts indefinitely, but the subject is allowed to make further saves vs spells at intervals. If one of these saves succeeds, the spell ends.\n  A creature with an INT score of 3-8 gains a new save once every month.\n  A creature with an INT of 9-12 gains a new save each week.\n  A creature with an INT of 13-18 gains a new save once every day.",
  "Sleep\nDuration: 4d4 turns\nRange: 240’\nA sleep spell causes a magical slumber to come upon creatures, excluding the undead. The spell may target either:\n  A single creature with 4+1 Hit Dice.\n  A total of 2d8 Hit Dice of creatures of 4 HD or lower each.\nWhen targeting creatures of 4 HD or less, the following rules apply:\n  Targets with the least HD are affected first.\n  Calculate monsters with less than 1 HD as having 1 HD and monsters with a bonus to HD as having the flat amount. (For example, a 3+2 HD monster would be calculated as having 3 HD.)\n  Rolled Hit Dice that are not sufficient to affect a creature are wasted.\nCreatures enchanted by this spell are helpless and can be killed instantly with a bladed weapon. Slapping or wounding awakens an affected creature.",
  "Floating Disc\nDuration: 6 turns\nRange: 6’\nThe caster conjures a slightly concave, circular disc of magical force that follows him or her about and carries loads.\n  The disc is 3 feet in diameter and 1 inch deep at its centre.\n  It can hold a maximum load of 5,000 coins (500 pounds).\n  The disc floats at waist height and remains level, floating along horizontally within spell range.\n  When the disc winks out at the end of the spell’s duration, anything it was supporting is dropped.",
  "Magic Missile\nDuration: 1 turn\nRange: 150’\nThis spell conjures a glowing dart of energy that the caster may choose to shoot at a visible target within range.\n  The missile hits unerringly (no attack roll or saving throw is required).\n  The missile inflicts 1d6+1 damage.\n  Higher level casters may conjure more missiles: two additional missiles are conjured per five experience levels the caster has gained (i.e. three missiles at 6th-10th level, five missiles at 11th-15th level, etc). Multiple missiles may be directed at a single target.",
  "Shield\nDuration: 2 turns\nRange: The caster\nShield creates an invisible field of force that protects the caster, granting an AC of 2 against missile attacks and AC 4 against other attacks.",
  "Ventriloquism\nDuration: 2 turns\nRange: 60’\nThe caster may make his or her voice appear to come from any location or source (e.g. a statue or animal) within the spell’s range."
];

/**
 * Include knave spells WITH rules
 */
export const knaveSpellAddendum =
  "“L” is a number equal to the caster’s level, an item is an object able to be lifted with one hand, and an object is anything up to human size. Unless otherwise noted, all spells with ongoing effects last up to L×10 minutes, and have a range of up to 40'. If a spell directly affects another creature, the creature may make a save to avoid it (as described previously). Success reduces or negates the spell’s effects.";
export const knaveSpells = [
  "Adhere: Object is covered in extremely sticky slime.",
  "Animate Object: Object obeys your commands as best it can. It can walk 15' per round.",
  "Anthropomorphize: A touched animal either gains human intelligence or human appearance for L days.",
  "Arcane Eye: You can see through a magical floating eyeball that flies around at your command.",
  "Astral Prison: An object is frozen in time and space within an invulnerable crystal shell.",
  "Attract: L+1 objects are strongly magnetically attracted to each other if they come within 10 feet.",
  "Auditory Illusion: You create illusory sounds that seem to come from a direction of your choice.",
  "Babble: A creature must loudly and clearly repeat everything you think. It is otherwise mute.",
  "Beast Form: You and your possessions transform into a mundane animal.",
  "Befuddle: L creatures of your choice are unable to form new short-term memories for the duration of the spell.",
  "Bend Fate: Roll L+1 d20s. Whenever you must roll a d20 after casting the spell, you must choose and then discard one of the rolled results until they are all gone.",
  "Bird Person: Your arms turn into huge bird wings.",
  "Body Swap: You switch bodies with a creature you touch. If one body dies, the other dies as well.",
  "Catherine: A woman wearing a blue dress appears until end of spell. She will obey polite, safe requests.",
  "Charm: L creatures treat you like a friend.",
  "Command: A creature obeys a single, three-word command that does not harm it.",
  "Comprehend: You become fluent in all languages.",
  "Control Plants: Nearby plants and trees obey you and gain the ability to move at 5 feet per round.",
  "Control Weather: You may alter the type of weather at will, but you do not otherwise control it.",
  "Counterspell: Make an opposed Intelligence save against the Intelligence of the caster of a nearby spell. You may do this out of turn as a reaction, or against an ongoing magical effect. On a success, you may cancel the spell.",
  "Deafen: All nearby creatures are deafened.",
  "Detect Magic: You hear nearby magical auras singing. Volume and harmony signify the aura’s power and refinement.",
  "Disassemble: Any of your body parts may be detached and reattached at will, without causing pain or damage. You can still control them.",
  "Disguise: You may alter the appearance of L characters at will as long as they remain humanoid. Attempts to duplicate other characters will seem uncanny.",
  "Displace: An object appears to be up to L×10' from its actual position.",
  "Earthquake: The ground begins shaking violently. Structures may be damaged or collapse.",
  "Elasticity: Your body can stretch up to L×10'.",
  "Elemental Wall: A straight wall of ice or fire L×40' long and 10' high rises from the ground.",
  "Filch: L visible items teleport to your hands.",
  "Fog Cloud: Dense fog spreads out from you.",
  "Frenzy: L creatures erupt in a frenzy of violence.",
  "Gate: A portal to a random plane opens.",
  "Gravity Shift: You can change the direction of gravity (for yourself only) up to once per round.",
  "Greed: L creatures develop an overwhelming urge to possess a visible item of your choice.",
  "Haste: Your movement speed is tripled.",
  "Hatred: L creatures develop a deep hatred of another creature or group of creatures and wish to destroy it.",
  "Hear Whispers: You can hear faint sounds clearly.",
  "Hover: An object hovers, frictionless, 2' above the ground. It can hold up to L humanoids.",
  "Hypnotize: A creature enters a trance and will truthfully answer L yes or no questions you ask it.",
  "Icy Touch: A thick ice layer spreads across a touched surface, up to L×10' in radius.",
  "Illuminate: A floating light moves as you command.",
  "Increase Gravity: The gravity in an area triples.",
  "Invisible Tether: Two objects within 10' of each other cannot be moved more than 10' apart.",
  "Knock: L nearby mundane or magical locks unlock.",
  "Leap: You can jump up to L×10' in the air.",
  "Liquid Air: The air around you becomes swimmable.",
  "Magic Dampener: All nearby magical effects have their effectiveness halved.",
  "Manse: A sturdy, furnished cottage appears for L×12 hours. You can permit and forbid entry to it at will.",
  "Marble Madness: Your pockets are full of marbles, and will refill every round.",
  "Masquerade: L characters’ appearances and voices become identical to a touched character.",
  "Miniaturize: You and L other touched creatures are reduced to the size of a mouse.",
  "Mirror Image: L illusory duplicates of yourself appear under your control.",
  "Mirrorwalk: A mirror becomes a gateway to another mirror that you looked into today.",
  "Multiarm: You gain L extra arms.",
  "Night Sphere: An L×40' wide sphere of darkness displaying the night sky appears.",
  "Objectify: You become any inanimate object between the size of a grand piano and an apple.",
  "Ooze Form: You become a living jelly.",
  "Pacify: L creatures have an aversion to violence.",
  "Phantom Coach: A ghostly coach appears until end of spell. It moves unnaturally fast over any terrain, including water.",
  "Phobia: L creatures become terrified of an object of your choice.",
  "Pit: A pit 10' wide and L×5' deep opens in the ground.",
  "Primeval Surge: An object grows to the size of an elephant. If it is an animal, it is enraged.",
  "Psychometry: The referee answers L yes or no questions about a touched object.",
  "Pull: An object of any size is pulled directly towards you with the strength of L men for one round.",
  "Push: An object of any size is pushed directly away from you with the strength of L men for one round.",
  "Raise Dead: L skeletons rise from the ground to serve you. They are incredibly stupid and can only obey simple orders.",
  "Raise Spirit: The spirit of a dead body manifests and will answer L questions.",
  "Read Mind: You can hear the surface thoughts of nearby creatures.",
  "Repel: L+1 objects are strongly magnetically repelled from each other if they come within 10 feet.",
  "Scry: You can see through the eyes of a creature you touched earlier today.",
  "Sculpt Elements: All inanimate material behaves like clay in your hands.",
  "Shroud: L creatures are invisible until they move.",
  "Shuffle: L creatures instantly switch places. Determine where they end up randomly.",
  "Sleep: L creatures fall into a light sleep.",
  "Smoke Form: Your body becomes living smoke.",
  "Snail Knight: 10 minutes after casting, a knight sitting astride a giant snail rides into view. He is able to answer most questions related to quests and chivalry, and may aid you if he finds you worthy.",
  "Sniff: You can smell even the faintest traces of scents.",
  "Sort: Inanimate items sort themselves according to categories you set. The categories must be visually verifiable.",
  "Spectacle: A clearly unreal but impressive illusion of your choice appears, under your control. It may be up to the size of a palace and has full motion and sound.",
  "Spellseize: Cast this as a reaction to another spell going off to make a temporary copy of it that you can cast at any time before this spell ends.",
  "Spider Climb: You can climb surfaces like a spider.",
  "Summon Cube: Once per second, (6 times per round) you may summon or banish a 3-foot-wide cube of earth. New cubes must be affixed to the earth or to other cubes.",
  "Swarm: You become a swarm of crows, rats, or piranhas. You only take damage from area effects.",
  "Telekinesis: You may mentally move L items.",
  "Telepathy: L+1 creatures can hear each other’s thoughts, no matter how far apart they move.",
  "Teleport: An object disappears and reappears on the ground in a visible, clear area up to L×40' away.",
  "Thaumaturgic Anchor: Object becomes the target of every spell cast near it.",
  "Thicket: A thicket of trees and dense brush up to L×40' wide suddenly sprouts up.",
  "Time Jump: An object disappears as it jumps L×10 minutes into the future. When it returns, it appears in the unoccupied area nearest to where it left.",
  "Summon Idol: A carved stone statue the size of a four poster bed rises from the ground.",
  "Time Rush: Time in a 40' bubble starts moving 10 times faster.",
  "Time Slow: Time in a 40' bubble slows to 10%.",
  "True Sight: You see through all nearby illusions.",
  "Upwell: A spring of seawater appears.",
  "Vision: You completely control what a creature sees.",
  "Visual Illusion: A silent, immobile, illusion of your choice appears, up to the size of a bedroom.",
  "Ward: A silver circle 40' across appears on the ground. Choose one thing that cannot cross it: Living creatures, dead creatures, projectiles or metal.",
  "Web: Your wrists can shoot thick webbing.",
  "Wizard Mark: Your finger can shoot a stream of ulfire-colored paint. This paint is only visible to you, and can be seen at any distance, even through solid objects.",
  "X-Ray Vision: You gain X-Ray vision."
];
