// ("Traits\n"
// "--------------------------------------------------\n"
// "A {background}. Wears {clothing} clothes, and has {speech} speech.\n"
// "Has a {physique} physique, a {face} face, {skin} skin and {hair} hair.\n"
// "Is {virtue}, but {vice}. Has been {misfortune} in the past.\n"
// "Favors {alignment}.")

export const traits = {
  physique: [
    "athletic",
    "brawny",
    "corpulent",
    "delicate",
    "gaunt",
    "hulking",
    "lanky",
    "ripped",
    "rugged",
    "scrawny",
    "short",
    "sinewy",
    "slender",
    "flabby",
    "statuesque",
    "stout",
    "tiny",
    "towering",
    "willowy",
    "wiry"
  ],

  face: [
    "bloated",
    "blunt",
    "bony",
    "chiseled",
    "delicate",
    "elongated",
    "patrician",
    "pinched",
    "hawkish",
    "broken",
    "impish",
    "narrow",
    "ratlike",
    "round",
    "sunken",
    "sharp",
    "soft",
    "square",
    "wide",
    "wolfish"
  ],

  skin: [
    "battle scar",
    "birthmark",
    "burn scar",
    "dark",
    "makeup",
    "oily",
    "pale",
    "perfect",
    "pierced",
    "pockmarked",
    "reeking",
    "tattooed",
    "rosy",
    "rough",
    "sallow",
    "sunburned",
    "tanned",
    "war paint",
    "weathered",
    "whip scar"
  ],

  hair: [
    "bald",
    "braided",
    "bristly",
    "cropped",
    "curly",
    "disheveled",
    "dreadlocks",
    "filthy",
    "frizzy",
    "greased",
    "limp",
    "long",
    "luxurious",
    "mohawk",
    "oily",
    "ponytail",
    "silky",
    "topknot",
    "wavy",
    "wispy"
  ],

  clothing: [
    "antique",
    "bloody",
    "ceremonial",
    "decorated",
    "eccentric",
    "elegant",
    "fashionable",
    "filthy",
    "flamboyant",
    "stained",
    "foreign",
    "frayed",
    "frumpy",
    "livery",
    "oversized",
    "patched",
    "perfumed",
    "rancid",
    "torn",
    "undersized"
  ],

  virtues: [
    "ambitious",
    "cautious",
    "courageous",
    "courteous",
    "curious",
    "disciplined",
    "focused",
    "generous",
    "gregarious",
    "honest",
    "honorable",
    "humble",
    "idealistic",
    "just",
    "loyal",
    "merciful",
    "righteous",
    "serene",
    "stoic",
    "tolerant"
  ],

  vices: [
    "aggressive",
    "arrogant",
    "bitter",
    "cowardly",
    "cruel",
    "deceitful",
    "flippant",
    "gluttonous",
    "greedy",
    "irascible",
    "lazy",
    "nervous",
    "prejudiced",
    "reckless",
    "rude",
    "suspicious",
    "vain",
    "vengeful",
    "wasteful",
    "whiny"
  ],

  speech: [
    "blunt",
    "booming",
    "breathy",
    "cryptic",
    "drawling",
    "droning",
    "flowery",
    "formal",
    "gravelly",
    "hoarse",
    "mumbling",
    "precise",
    "quaint",
    "rambling",
    "rapid-fire",
    "dialect",
    "slow",
    "squeaky",
    "stuttering",
    "whispery"
  ],

  background: [
    "alchemist",
    "beggar",
    "butcher",
    "burglar",
    "charlatan",
    "cook",
    "cultist",
    "gambler",
    "herbalist",
    "magician",
    "mariner",
    "mercenary",
    "merchant",
    "outlaw",
    "performer",
    "pickpocket",
    "smuggler",
    "student",
    "tracker"
  ],

  misfortunes: [
    "abandoned",
    "addicted",
    "blackmailed",
    "condemned",
    "cursed",
    "defrauded",
    "demoted",
    "discredited",
    "disowned",
    "exiled",
    "framed",
    "haunted",
    "kidnapped",
    "mutilated",
    "poor",
    "pursued",
    "rejected",
    "replaced",
    "robbed",
    "suspected"
  ],

  alignment: [
    "law",
    "law",
    "law",
    "law",
    "law",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "chaos",
    "chaos",
    "chaos",
    "chaos",
    "chaos"
  ]
};

// Crab-People Traits are different from other classes since they are
// so radically different from other classes in appearance and social
// status.
// ("Traits\n"
// "--------------------------------------------------\n"
// "A {background}. Wears {clothing -> rags} rags.\n"
// "Has a {physique} physique, a {face} face, and a {skin -> shell} shell.\n"
// "Is {virtue}, but {vice}. Has been {misfortune} in the past.\n"
// "Favors {alignment}.")
export const crabPersonTraits = {
  physique: [
    "athletic",
    "brawny",
    "gaunt",
    "hulking",
    "lanky",
    "ripped",
    "rugged",
    "short",
    "stout",
    "tiny",
    "towering"
  ],

  face: [
    "blunt",
    "elongated",
    "broken",
    "impish",
    "narrow",
    "round",
    "sunken",
    "sharp",
    "square",
    "wide"
  ],

  shell: [
    "barnacled",
    "crusted",
    "battle scarred",
    "dark",
    "blue",
    "pale",
    "perfect",
    "pierced",
    "reeking",
    "rough",
    "smooth",
    "war painted",
    "weathered",
    "bumpy",
    "jagged",
    "cleft",
    "cracked"
  ],

  rags: [
    "bloody",
    "filthy",
    "stained",
    "frayed",
    "oversized",
    "patched",
    "rancid",
    "torn",
    "undersized"
  ],

  virtues: [
    "ambitious",
    "cautious",
    "courageous",
    "courteous",
    "curious",
    "disciplined",
    "focused",
    "generous",
    "gregarious",
    "honest",
    "honorable",
    "humble",
    "idealistic",
    "just",
    "loyal",
    "merciful",
    "righteous",
    "serene",
    "stoic",
    "tolerant"
  ],

  vices: [
    "aggressive",
    "arrogant",
    "bitter",
    "cowardly",
    "cruel",
    "deceitful",
    "flippant",
    "gluttonous",
    "greedy",
    "irascible",
    "lazy",
    "nervous",
    "prejudiced",
    "reckless",
    "rude",
    "suspicious",
    "vain",
    "vengeful",
    "wasteful",
    "whiny"
  ],

  background: [
    "gladiator",
    "slave",
    "servant",
    "laborer",
    "ditcher",
    "beggar",
    "scullion",
    "gravedigger",
    "bodyguard",
    "fisher",
    "pearl diver"
  ],

  misfortunes: [
    "abandoned",
    "addicted",
    "blackmailed",
    "condemned",
    "cursed",
    "defrauded",
    "demoted",
    "discredited",
    "disowned",
    "exiled",
    "framed",
    "haunted",
    "kidnapped",
    "mutilated",
    "pursued",
    "rejected",
    "replaced",
    "robbed",
    "suspected"
  ],

  alignment: [
    "law",
    "law",
    "law",
    "law",
    "law",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "neutrality",
    "chaos",
    "chaos",
    "chaos",
    "chaos",
    "chaos"
  ]
};
